spring:
  # Mysql 用户
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-config.yaml
  # SQLite 用户
#  datasource:
#    # SQLite相关配置，引用项目中的数据库文件
#    driver-class-name: org.sqlite.JDBC
#    url: jdbc:sqlite::resource:static/sqlite/increment-backup.db
#    username:
#    password:



