# Tomcat
server:
  port: 8899
# spring
spring:
  profiles:
    active: database
  # 指定静态资源的路径
  web:
    resources:
      static-locations: classpath:/static/dist

#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 线程池设置
ibs:
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10
    queue-capacity: 100

#mybatis:
#  mapper-locations: classpath*:mapper/**/*.xml
