# Tomcat
server:
  port: 8899

#spring
spring:
  datasource:
    #引用项目中的数据库文件
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite::resource:static/sqlite/increment-backup.db
    username:
    password:
  # 指定静态资源的路径
  web:
    resources:
      static-locations: classpath:/static/dist

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 线程池设置
ibs:
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10
    queue-capacity: 100

#mybatis:
#  mapper-locations: classpath*:mapper/**/*.xml
