spring:
  # Mysql 用户（分表）
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-config.yaml
  # Mysql 用户（不分表）
#  datasource:
#    username: root
#    password: 12345678
#    url: jdbc:mysql://127.0.0.1:3308/increment-backup?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    hikari:
#      connection-test-query: select 1
#      connection-timeout: 20000
#      idle-timeout: 300000
#      maximum-pool-size: 5
#      minimum-idle: 5
  # SQLite 用户
#  datasource:
#    # SQLite相关配置，引用项目中的数据库文件
#    driver-class-name: org.sqlite.JDBC
#    url: jdbc:sqlite::resource:static/sqlite/increment-backup.db
#    username:
#    password:



